name: iConomy
main: com.iCo6.iConomy
version: 6.0
authors: [Nijikokun,SpaceManiac]
commands:
    money:
      aliases: [iConomy,iCo]
      description: Check / Distrobute currency.
      permission: iconomy.access
      usage: